### ISSUE TITLE
Update workflow yml files to move jdk16 to jdk17

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/build-jdk#43]
In yaml files inside of https://github.com/adoptium/build-jdk/blob/master/.github/workflows/
where ever we reference jdk16u, we should switch to jdk17u

Example: https://github.com/adoptium/build-jdk/blob/master/.github/workflows/nightly.yml#L13
should be changed to `javaToBuild: [jdk11u, jdk17u]

**Comment by sayali0710** [comment]
Will be working ont his

**Comment by smlambert** [comment]
Wonderful, thanks @sayali0710 !

**Comment by smlambert** [comment]
Closed via https://github.com/adoptium/build-jdk/pull/45
